#############
# Main model:

## Specify the model to use for the main chat
# model: gemini/gemini-2.0-flash-exp
model: free-r1
# model: gemini/gemini-2.5-pro-exp-03-25

# model: openrouter/deepseek/deepseek-r1:free
# model: openai/google/gemini-2.5-pro-exp-03-25
# model: openai/google/gemini-2.0-flash-thinking-exp-01-21
# model: openrouter/google/gemini-2.0-flash-thinking-exp:free
# model: openrouter/google/gemini-2.5-pro-exp-03-25:free

editor-model: free-2.5-pro
# editor-model: gemini/gemini-2.0-flash-exp
# editor-model: openrouter/deepseek/deepseek-chat:free
# editor-model: gemini/gemini-2.5-pro-exp-03-25

# weak-model: openrouter/google/gemini-2.0-flash-lite-preview-02-05:free
# weak-model: openrouter/mistralai/mistral-7b-instruct:free
# 
weak-model: gemini/gemini-2.0-flash-exp

alias:
  - free-2.5-pro:gemini/gemini-2.5-pro-exp-03-25
  - free-2.0:gemini/gemini-2.0-flash-exp
  - free-optimus:openrouter/openrouter/optimus-alpha
  - free-r1:openrouter/deepseek/deepseek-r1:free

## Only work with models that have meta-data available (default: True)
show-model-warnings: false

## Suggested number of tokens to use for repo map, use 0 to disable
map-tokens: 4096

## Use colors suitable for a dark terminal background (default: False)
dark-mode: true

## Show diffs when committing changes (default: False)
show-diffs: true

## Only consider files in the current subtree of the git repository
subtree-only: true

## Enable/disable auto commit of LLM changes (default: True)
auto-commits: false

## Permanently disable analytics
analytics-disable: true

read: ~/CONVENTIONS.md
