[[language]]
name = "rust"
language-servers = ["rust-analyzer" ]
auto-format = true
indent = { tab-width = 4, unit = "t" }
[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "html"
auto-format = true
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
auto-format = true
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "typescript"
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "javascript"
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
auto-format = true
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
auto-format = true
formatter = { command = "pg_format" }
language-servers = [ "sql-language-server" ]
